name: Keep Sellstream App Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Sellstream App
        run: |
          curl -X GET https://sellstreams1.onrender.com/doc/
